language: node_js
node_js:
  - 10

services:
  - docker


after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t $DOCKER_USER/$DOCKER_REPO .
  - docker push $DOCKER_USER/$DOCKER_REPO

